spring.application.name=Project
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_SECRET_KEY}
spring.security.oauth2.client.registration.google.redirect-uri=${GOOGLE_REDIRECT_URL}

spring.tmdb.access.token=${TMDB_ACCESS_TOKEN}

spring.cache.caffeine.spec=expireAfterWrite=86400s

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml